### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ebgoldstein** [Doodleverse/segmentation_gym#101]
I think once this is reviewed and merged, it is time for a 'release'. Coinciding with the paper.. I think we have now gotten Gym to the point where is "stable" (jeez, famous last words!)

I'll then tag the release in the new zenodo release for the test dataset

_Originally posted by @dbuscombe-usgs in https://github.com/Doodleverse/segmentation_gym/issues/99#issuecomment-1286164499_

**Comment by dbuscombe-usgs** [comment]
https://github.com/Doodleverse/segmentation_gym/releases/tag/v1.0.0 🎉
