### ISSUE TITLE
resizing images in seg_image_in_folder

### ISSUE THREAD

**Issue by ebgoldstein** [Doodleverse/segmentation_gym#11]
this is from #4 ...

> offset is noticeable for the light blue regions. (more in y axis, which is scaled from 800px -> 700px.... than in the x (which is scaled from 1000px - 1024px). Note also that when i examined the output *.png from train_resunet.py, i could not detect any offset in labels (i mean, that makes sense.. the code is different.. but i just mention this for completeness)...
>
>![offsetEx](https://user-images.githubusercontent.com/5330599/136557077-20a95346-0250-46db-b002-f763d019b8b4.jpg)

**Comment by dbuscombe-usgs** [comment]
See my latest commit, which now has a rudimentary (but working) re-implementation without the previous "resize and crop" commands .... now it just resizes
