### ISSUE TITLE
How to use make_nd_dataset with images with more than 3 channels

### ISSUE THREAD

**Issue by mvilar22** [Doodleverse/segmentation_gym#127]
So I have a bunch of _jpgs_ files, but I want to add a 4th channel. Do I save that 4th channel as a separate _jpg_? Should I try to add the 4th channel as an array to the _npz_ files after running the script? 

The script seems to be able to include images with more than 3 channels but I don't get how, maybe when it asks for more images? 

Thanks!

**Comment by dbuscombe-usgs** [comment]
Hi @mvilar22 thanks for the question. That should be possible using `make_nd_dataset.py`. Add your first set of images, then when it prompts you for additional imagery, point it to a folder that contains jpegs for your 4th band. This workflow should work if the jpegs are grayscale, i.e. they contain only one band.

You should have equal numbers of images and 4th band images. They should be named such that when both lists of files are sorted (we use `natsort`), the order of images in both lists make viable pairs. Let me know how you get on?

**Comment by mvilar22** [comment]
Hi, thanks for the answer! 

I managed to run the script and train just fine, however I run into a bit of a conflict when I try to run the model on the test dataset.

When I run`seg_images_in_folder.py` I get an error that tells me to check the config file and the path. Now, this is probably because the test images only have 3 bands, I have another folder with the extra band but the script does not ask for further images, like `make_nd_dataset.py`. 

Should I manually create the npz to be like the npz provided for train or is there a way to use  `make_nd_dataset.py` to process the test dataset, maybe indicating no validation split? 

Thanks!

**Comment by dbuscombe-usgs** [comment]
Hi @mvilar22 nice job getting it to work! It's a little clunky, but for inference, I prepare the npz files the model expects using the `utils` function, `preprocess_data` https://github.com/Doodleverse/segmentation_gym/blob/main/utils/preprocess_data.py

You would run it using flag 0, for custom npz files made using multiple bands, i.e.

`python preprocess_data.py -t 0`

It's calling this script, https://github.com/Doodleverse/doodleverse_utils/blob/main/doodleverse_utils/merge_nd_inputs4pred.py

It works in the same way that `make_nd_datasets` does. It asks for your 3-band images first, then your 1-band images, and makes npz files from them by merging the bands. Let me know how well it works!

**Comment by mvilar22** [comment]
Hi again!

Thanks for the help, besides a true divide warning and black pixels showing up randomly in the images it worked. 

I guess if I want to deploy the model I need to use `gen_saved_model.py` and emulate `merge_nd_inputs4pred.py` to wrap the input but that's a problem for another time.

Thanks for giving me a hand! I am closing the issue.
