### ISSUE TITLE
npz format for gen_images_and_labels

### ISSUE THREAD

**Issue by mvilar22** [Doodleverse/segmentation_gym#130]
Hi there, I have about 15k images that are already labelled, in order to use this images with **gen_images_and_labels.py** I need a npz file for each image. I have managed to create them like this:

```
i = 0
for filename in os.listdir(src):
    if filename[-3:] == "png":
        npz = {}
        #open the image, turn it into a numpy array 
        img = cv2.imread(src+filename.split(".")[0]+'.jpg')
        img = np.asarray(img)
        npz['image'] = img
        #open the label, turn it into a numpy array
        label = cv2.imread(src+filename)
        label = np.asarray(label)
        
        npz['label'] = label
        npz['classes'] = ['vegetation' 'background']
        np.savez_compressed(src+filename.split(".")[0]+'.npz', npz, **npz)
        print(i)
        i+=1
```

However, when I run the script I check the overlay images generated and they are "blue" with only one class present. 

The labels I am feeding are png like this:

![7481_PepperTimeLapse](https://github.com/Doodleverse/segmentation_gym/assets/129166635/70f2695f-ccca-4ac1-94ec-81f481029982)

I don't know if this is correct, the script seems to one-hot encode the labels so I don't think I should feed the script labels already encoded. What am I missing?

Thanks!

**Comment by ebgoldstein** [comment]
Hi @mvilar22 - can you provide a few example image-label pairs for us to experiment with?

**Comment by dbuscombe-usgs** [comment]
Hi @mvilar22 , any reason why you can't use "make_nd_daraset.py" for this task? It will ask for your greyscale labels and images, and make npz files for gym. You need greyscale labels. If you need to make your own npz files, the arrays must be called 'arr_0' and 'arr_1'

**Comment by mvilar22** [comment]
Hi @ebgoldstein, here are some examples. The images are taken from time lapse videos of plants growing. There are only 2 classes, background and vegetation.

[fewExamples_PepperTimeLapse.zip](https://github.com/Doodleverse/segmentation_gym/files/11514552/fewExamples_PepperTimeLapse.zip)

@dbuscombe-usgs haven't really thought about that, so I can skin this "step" and use **make_nd_dataset.py** directly with the one-hot encoded labels and the images?

I was just trying to recreate the process as if I had doodled the images but now it seems a bit redundant

**Comment by mvilar22** [comment]
Hi there, so I did as @dbuscombe-usgs suggested and I ran into some issues.

I one hot encoded the labels and ran **make_nd_dataset.py** but an error popped up:

![image](https://github.com/Doodleverse/segmentation_gym/assets/90894721/bd3f1a55-e123-4560-ab83-36a7d31c8113)

The script did resize the images since I have a resized_images folder with all the images but the resized_labels folder is empty and the script says there are 0 labels, as you can see in the photo.

Maybe there is a problem in the one hot encoding process, I use this code to create the jpg labels:

````
for filename in tqdm.tqdm(os.listdir(src), desc="One-hot encoding labels"):
    #Load image and turn it to RGB  
    img = cv2.imread(os.path.join(src, filename))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    #Find the image dimensions
    h, w, c = img.shape

    #Define the colors that represent classes
    blue = (51,102,204)
    red = (220, 57, 18)

    #Create masks for each class
    mask_1 = np.all(img==blue, axis=-1)
    mask_2 = np.all(img==red, axis=-1)

    #Create a class map assigning indexes according to the class masks 
    indices = np.zeros((h,w), dtype=np.uint8)
    indices[mask_1] = 1
    indices[mask_2] = 0
    #one-hot array 
    nx, ny = indices.shape
    lstack = np.zeros((nx, ny, 2))
    #Assign values
    lstack[:,:,:2] = (np.arange(2) == indices[...,None]-1).astype(int)
    #Obtain the labels
    l = np.argmax(lstack,-1).astype('uint8')

    cv2.imwrite(output_path + filename, l)
````

The final part of the code comes from **gen_images_and_labels.py** I did test the code with an image and label I had already labelled using dashdoodler and it produced the same jpg, I checked comparing each individual channel of both images with opencv.

Any insight into what am I surely doing wrong? 

Thanks!

**Comment by dbuscombe-usgs** [comment]
Can you provide a small sample of images and corresponding labels? It's not clear to me why you need to use opencv commands to make jpegs

**Comment by dbuscombe-usgs** [comment]
If the program can't find the labels, it is probably because you have either named them in such a way that the can't be paired with imagery using a natural sort, or the images are in the wrong folder structure or something

**Comment by ebgoldstein** [comment]
@mvilar22 - I am looking at the images in the zip file:

Q for you - were these image-label pairs made using [Doodler](https://github.com/Doodleverse/dash_doodler) ?

**Comment by ebgoldstein** [comment]
no bother at all!

yes - try to rename the files,  make them jpegs.. then try `make_nd_dataset.py`

let me know how it works!

**Comment by mvilar22** [comment]
As it turns out, the labels were indeed pngs, I could have sworn they were jpgs but I stand corrected, now that they are jpgs `make_nd_dataset.py` does work!

I am running into a little problem when running` train_model.py` with the ptxas binaty, the path and a message saying there is no space left on the device, but that seems like a me problem so I am going to close the issue.

Thank you so much for the help!!

**Comment by ebgoldstein** [comment]
:+1: - keep us posted how you get on!

**Comment by mvilar22** [comment]
While the training completed without issue, it seems my labeling process was wrong. All the images feed to the net had their pixels belong to a single class, which is obviously wrong. **make_nd_dataset.py** does tells me the images belong to 1 classes, but if I recall correctly it says that even if there are more classes. 

 This is how I was making the grayscale jpg labels: 

```
    #Load the image and convert it to RGB  
    img = cv2.imread(os.path.join(src, filename))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    #Get the dimensions of the image
    h, w, c = img.shape

    #Define the colors representing the classes
    blue = (51,102,204)
    red = (220, 57, 18)

    #Create masks for each class
    mask_1 = np.all(img==blue, axis=-1)
    mask_2 = np.all(img==red, axis=-1)

    #Create a class map with the dimensions of the image, assigning indices based on the class masks
    indices = np.zeros((h,w), dtype=np.uint8)
    indices[mask_1] = 1
    indices[mask_2] = 0
    #Create a one-hot label matrix with the dimensions of the class map
    nx, ny = indices.shape
    lstack = np.zeros((nx, ny, 2))
    #Assign values
    lstack[:,:,:2] = (np.arange(2) == indices[...,None]-1).astype(int)
    #Get the labels
    l = np.argmax(lstack,-1).astype('uint8')

    cv2.imwrite(output_path + filename.split('.')[0]+'.jpg', l)
```

The images that I am working with are png with only two colors, like this:
 
![72_Wheat2013TimeLapse](https://github.com/Doodleverse/segmentation_gym/assets/90894721/07b004aa-aaa2-424b-b3a6-d0947861b423)

I have seen that the scripts have been updated recently and the there is a new **make_dataset.py**, but the changes don't seem to be related with my issue. 

While debugging the code, up to the creation of _indices_ it seems to work as intended, because if I apply _indices_ as a mask I get only the blue pixels. That leads me to believe the problem resides in these lines:


```
    nx, ny = indices.shape 
    lstack = np.zeros((nx, ny, 2)) 
    lstack[:,:,:2] = (np.arange(2) == indices[...,None]-1).astype(int) 
    l = np.argmax(lstack,-1).astype('uint8')
``` 
As I understand it, _lstack_ should be an int matrix with the same dimensions as _indices_. It should be filled with the result of `np.arange(2)== indices[..,None]-1` that produces either True or False. 

Since it is turning it into ints, the booleans turn to 0 or 1. `indices[..,None]-1` should be -1 for the values that were 0 in _indices_ and 0 for the values that were 1.

Then in the comparison, you get `[0 0] `for a value of -1 and `[1 0]` for the value of 0. Then _l_ is created with the index for the maximum value of _lstack_. If I am not mistaken that is never going to be 1, because _lstack_ is either `[0 0]` or `[1 0]` so the max is always in the position 0. 

However, this code snippet comes from **gen_images_and_labels.py** that does work, so I don't know what I am missing. 

In the mean time I will update to use the new scripts and try training again, but without the -1 when the values are assigned to _lstack_

**Comment by ebgoldstein** [comment]
@mvilar22 - I want to clarify, `make_dataset.py` does not take one-hot encoded labels, it takes grayscale labels (two dimensional jpgs, so M x N) . I think you need to adjust your code above to make sure it is not creating one-hot encoded labels...

**Comment by mvilar22** [comment]
The issue is that every pixel of every image belong to the same class.  I haven't tried to predict on the test dataset because every picture provided in the training and validation dataset only had one class and the training was useless. 

In the zip attached I have included some images, labels and the config file. 
[samples.zip](https://github.com/Doodleverse/segmentation_gym/files/11654451/samples.zip)

I am training now with a modification to the code I posted before, but apparently using mirrored strategy eagerly has significant overhead and each epoch seems to be about 8h so I don't know if I have actually solved the issue. 

Here are the same image-label pairs but with the "new" code, just in case. 
[rectified-samples.zip](https://github.com/Doodleverse/segmentation_gym/files/11654540/rectified-samples.zip)

**Comment by ebgoldstein** [comment]
Hi @mvilar22 

First, the labels in the `samples.zip` folder appear as all 0 to me...
```
from PIL import Image
import numpy as np
from matplotlib import image
from matplotlib import pyplot

filename = "samples/labels/59_SunflowerTimeLapse.jpg"
with Image.open(filename) as im:
    width, height = im.size
    pixel_values = list(im.getdata())

print(np.unique(pixel_values))
pyplot.imshow(im)
pyplot.show()
```

![image](https://github.com/Doodleverse/segmentation_gym/assets/5330599/351d7f3a-2acf-4193-b6c1-59864e9fb2c3)


However, in the rectified sample folder, i do see multiple values in the image:

```
filename = "rectified-samples/labels/59_SunflowerTimeLapse.jpg"
with Image.open(filename) as im:
    width, height = im.size
    pixel_values = list(im.getdata())

pyplot.imshow(im)
pyplot.show()
```
![image](https://github.com/Doodleverse/segmentation_gym/assets/5330599/d0ef1379-5ff6-4401-b664-cc25e72026d6)

Gym should work with these images in the `rectified_samples` folder (but note that these do not have `_label` in the name of the file, so you might want to add that. 

At this point - if it's ok with you - i am going to close the issue : you have made images that should work with Gym.. If you run into a problem with training, let us know (and include the config, sample images). 

let us know and good luck
