### ISSUE TITLE
Segformer prediction using `seg_images_in_folder`

### ISSUE THREAD

**Issue by ebgoldstein** [Doodleverse/segmentation_gym#139]
There is some bug when using a trained segformer model for seg_images_in_folder`. I have the same behavior as @tsotop described in this discussion https://github.com/Doodleverse/segmentation_gym/discussions/138

**Comment by ebgoldstein** [comment]
@dbuscombe-usgs, 2 Qs for you:
1) Have you used a segformer model when running `seg_images_in_folder` ?
2) How have you done prediction with a segformer model?

**Comment by ebgoldstein** [comment]
this might be related to model saving.. see this link -> github. com/ huggingface/ transformers/issues/18582
(with spaces added to avoid a hard link to that issue)

**Comment by dbuscombe-usgs** [comment]
Super late to the party here but yes I've seen that warning since the start, and no, its never been a problem for me. Virtually all my models are now segformers and the `do_seg` function from `doodleverse_utils` still forms the basis of this and many other model.predict implementations using segformers.

So, lmk if this is still an issue for you?

**Comment by ebgoldstein** [comment]
**cautionary tale:**

:skull_and_crossbones: :skull_and_crossbones: :skull_and_crossbones: :skull_and_crossbones: 

ok, to rehash the problem i was having:
- Seg_images_in_folder did not perform well with segformer models in some unknown situations... the images were blotchy, predictions were not as good as the model training curves suggested.

what I knew:
- Weights were saved correctly after `train` script. I knew this because a trained segformer model could be used for single image predictions, and worked as expected. I.e., loading the untrained segformer model, then attaching weights (*.h5) using `model.load_weights`. 
- weights were loaded and attached correctly during `seg_images in folder`. I knew this by using code like below to print the last layer weights:
```
    MW = model.layers[-1].get_weights()
    print(MW[-1])
```
an untrained model would have an array of 0s, with a length according to NCLASSES. this statement above can be used to verify that trained (non 0) weights are in fact used. I put it in the last lines of `seg_images_in_folder`, actually in the loop that runs through all images to be segmented to make sure the trained model was used for each do_seg call.

My guess at this point was that something was awry in `do_seg`... i did a detailed read through the entire code, no problems.

it turns out TestTime augmentation was set to true, but the model was not trained with any vertical flips (only horizontal).. so the vertical flips were likely confuding the predictions... 

**Moral of the story - read through your config file... many problems are in the config (or the data!), and not in the code.. the config and data are also easier to debug**

:skull_and_crossbones: :skull_and_crossbones: :skull_and_crossbones: :skull_and_crossbones:
