### ISSUE TITLE
add windowing in implementation, optionally with tapering

### ISSUE THREAD

**Issue by ddbuscombe** [Doodleverse/segmentation_gym#14]

**Comment by dbuscombe-usgs** [comment]
implement the tapering with windowing following [this method](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0229839)

**Comment by dbuscombe-usgs** [comment]
see [here](https://github.com/MARDAScience/BlurCropperDetector/blob/main/BlurCropperDetector.ipynb)
