### ISSUE TITLE
links to wiki pages

### ISSUE THREAD

**Issue by cresposito** [Doodleverse/segmentation_gym#140]
Not a big issue, but:

The hyperlinks to the wiki sections in the [How to Use](https://github.com/Doodleverse/segmentation_gym#how-to-use) guide are not correct because they don't include the leading zeros on the wiki section URLs.

**Comment by ebgoldstein** [comment]
thanks for pointing this out  @cresposito !

**Comment by dbuscombe-usgs** [comment]
I plan to overhaul the wiki soon, so I will update these links at that time. Thanks again
