### ISSUE TITLE
ModuleNotFoundError for 'doodleverse_utils' when running seg_images_in_folder.py

### ISSUE THREAD

**Issue by joy91269** [Doodleverse/segmentation_gym#143]
Hello,

I'm currently trying to use your project and ran into an issue when executing the script seg_images_in_folder.py. It seems that the script is dependent on a module named doodleverse_utils, which is not available in my environment. Here's the error message I received:

Traceback (most recent call last):
  File "seg_images_in_folder.py", line 247, in <module>
    from doodleverse_utils.imports import *
ModuleNotFoundError: No module named 'doodleverse_utils'

I've checked the project documentation and couldn't find instructions on how to install or obtain this module. Could you please provide guidance on how to resolve this issue? Specifically, I'm interested in knowing if doodleverse_utils is a package that should be installed separately, or if it's part of the project and perhaps missing from the repository.

Any assistance or guidance you can provide would be greatly appreciated, as I'm eager to fully utilize your project for my work.

Thank you very much for your help and for the work you've put into this project.

**Comment by dbuscombe-usgs** [comment]
Use `pip install doodleverse_utils` (apologies, I will update the install instructions)

**Comment by dbuscombe-usgs** [comment]
(this is just this package, right here in this repo https://github.com/Doodleverse/doodleverse_utils)

**Comment by joy91269** [comment]
Thanks,
and please add
pip install scikit-image
pip install matplotlib
as well. Thanks for your reply.

**Comment by joy91269** [comment]
Step 2: from your segmentation_gym root folder, e.g. /Users/Someone/github_clones/segmentation_gym, in an activated gym conda environment, run python make_nd_dataset.py.
And about this step, just want to make sure did you change the name of the python file from make_nd_dataset.py to train_model.py, or is there any other places i should download the make_nd_dataset.py file? Thanks.

**Comment by dbuscombe-usgs** [comment]
Ah, that's a typo. The script is now called `make_dataset.py`

**Comment by joy91269** [comment]
Thanks,
and this one need : pip install natsort
train_models.py need: pip install pandas
please update it in the instructions as well lol

Step 3: run python train_model.py.

    It will first prompt you to select the output directory where model training files were written to, e.g. /Users/Someone/model_from_scratch_test.
    Then it will ask for a config file. Select the hatteras_l8_resunet.json config file, e.g. /Users/Someone/my_segmentation_gym_datasets/config/hatteras_l8_resunet.json.
And in this part, you change it into select train data file, then val data file , then config.

In this part i just choose train_data folder and there is the error:(gym) jzdgt@cengr-4v7pdf3:~/Downloads/Models/segmentation_gym$ python train_model.py
/home/jzdgt/Downloads/Models/segmentation_gym/model_from_scratch_test/train_data
/home/jzdgt/Downloads/Models/segmentation_gym/model_from_scratch_test/val_data
/home/jzdgt/Downloads/Models/segmentation_gym/my_segmentation_gym_datasets_v5/config/hatteras_l8_resunet.json
Using GPU
Using single GPU device
2024-03-18 15:28:34.201669: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-18 15:28:34.239835: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-18 15:28:34.837340: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Transformers library did not load
Version:  2.13.1
Eager mode:  True
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Making new directory for example model outputs: /home/jzdgt/Downloads/Models/segmentation_gym/my_segmentation_gym_datasets_v5/modelOut
2024-03-18 15:28:35.792516: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21873 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:17:00.0, compute capability: 8.6
Traceback (most recent call last):
  File "train_model.py", line 593, in <module>
    list_ds = tf.data.Dataset.list_files(train_filenames, shuffle=False) ##dont shuffle here
  File "/home/jzdgt/miniconda3/envs/gym/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1303, in list_files
    assert_not_empty = control_flow_assert.Assert(
  File "/home/jzdgt/miniconda3/envs/gym/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/jzdgt/miniconda3/envs/gym/lib/python3.8/site-packages/tensorflow/python/ops/control_flow_assert.py", line 102, in Assert
    raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b'No files matched pattern: '
Should i choose the train_images instead of the whole train_data folder?

**Comment by dbuscombe-usgs** [comment]
Thanks for these details. I've known about the issues with the out-of-date readme and wiki and instructions for a while but have zero bandwidth to maintain these projects actively - I'll get there. Thanks for your patience.

For the test set, I did update the instructions recently - please try them. Thank you https://github.com/Doodleverse/segmentation_gym?tab=readme-ov-file#test-dataset

**Comment by dbuscombe-usgs** [comment]
Closing issue because there are several Issues here. Please reopen a new issue if you have a new issue. Thanks
