### ISSUE TITLE
Issue with Installation

### ISSUE THREAD

**Issue by rtmccune** [Doodleverse/segmentation_gym#145]
**Describe the bug**
I was attempting to follow the conda installation instructions on the README, but I am getting the following message after importing tensorflow post-installation.

`(gym) rmccune@ccee-dt-055:~/Documents/segmentation_gym$ python -c "import tensorflow as tf"
2024-04-03 20:32:36.738091: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-03 20:32:37.487227: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
`
I have not ran into this bug before when installing tensorflow, but I was wondering if you have any solutions? 

**Desktop**
 - OS: Ubuntu 22.04
 - GPU: NVIDIA Quadro K6000

**Comment by ebgoldstein** [comment]
hi @rtmccune , I have not seen this before, and have no good solution. have you tried any possible solutions?

When i googled the last sentence of your issue, i did find some hits in the form of GH issues, with a few people chiming in about how to solve it (path wrangling)...here is the link, with some spaces entered in the URL so we don't link directly to that issue: 
github.com/ tensorflow /tensorflow/issues/61468
github.com/ tensorflow/tensorflow/issues/ 64809

**Comment by dbuscombe-usgs** [comment]
This isn't a bug.  It's just a warning from tensorflow. I've seen it every time I run a gym program for well over a year. It's not something I seem to be able to control but since it is just a warning and doesn’t affect model training or accuracy I'm inclined to just ignore it since it doesn't seem to be a problem
