### ISSUE TITLE
IoU differs between model.evaluate and model.predict (due to file reading?)

### ISSUE THREAD

**Issue by ddbuscombe** [Doodleverse/segmentation_gym#4]
@ebgoldstein 
on your FRF dataset the validation stats are 
`loss=0.1838, Mean IOU=0.8072, Mean Dice=0.8162`
using `"TARGET_SIZE": [768,1024]`

However, using the model in prediction mode, which involves `train_ds.take(10)`, it yields much lower scores:

`Mean IoU (validation subset)=0.492`
`Mean IoU (train subset)=0.533`

`seg_images_in_folder` which involves the function `seg_file2tensor_3band` to read the image in, then model.predict, then resize output, yields much lower scores:

I have found this same problem with every multicass dataset (it may be a problem with the binary datasets but is masked by test-time augmentation)

Perhaps the issue is the way `seg_file2tensor_3band` resizes the image using a `tf.image.crop_to_bounding_box` command? All I know is that `model` wants a tensorflow tensor of shape B x M x N x 3 images, with M, N = TARGET_SIZE ... there are many ways to do that

I'll already ruled out the standardization (I think), there are 2 options:
`image = tf.image.per_image_standardization(image)`
and
 `image = standardize(image.numpy())`
 
 and I use the latter because that is what I use in training (and because I deal with 1-band images simply by stacking them !!!) - I tested on satellite data and it didnt make a difference

**Comment by dbuscombe-usgs** [comment]
Standardization is not the issue here.

Resizing / cropping the likely culprit
