### ISSUE TITLE
Standardize color ramp for all plots with Doodler

### ISSUE THREAD

**Issue by ebgoldstein** [Doodleverse/segmentation_gym#7]
- [x] makedataset creates plots
- [x] train_resunet makes plots
- [x] seg images makes plots

**Comment by dbuscombe-usgs** [comment]
the function call to implement is this

`color_label = label_to_colors(est_label, tf.cast(img[:,:,0]==0,tf.uint8), alpha=128, colormap=class_label_colormap, color_class_offset=0, do_alpha=False)`

the trick here is ` tf.cast(img[:,:,0]==0,tf.uint8)` that turns the mask or "where the image is black" or `img[:,:,0]==0` into an 8-bit tensor
