### ISSUE TITLE
Wiki Improvement: A new page with a walkthrough of using the test dataset

### ISSUE THREAD

**Issue by 2320sharon** [Doodleverse/segmentation_gym#70]
# Wiki Improvement: New Page that walks the user through using the test dataset
Currently, there is no page in Gym that guides the user through using gym with a sample dataset. [Directory-Structure-and-Tests](https://github.com/Doodleverse/segmentation_gym/wiki/Directory-Structure-and-Tests) shows the user how to structure their test data, but it is not obvious to the user to click this page first to get the sample dataset and run gym.

## Suggested Solution
We create a page called `Gym Walkthrough` that walks the user step by step through using Gym with the [test dataset](https://zenodo.org/record/5895128). This walkthrough would include diagrams and screenshots that show the user what they should expect to occur at every step from downloading the test dataset to using the scripts on the test dataset. I think it would also be useful to also explain what each of the scripts in the `utils` folder would be best used for as it is currently not immediately clear to the user. The explanation of what each of the scripts in the `utils` folder does could be a different page as well.

**Comment by dbuscombe-usgs** [comment]
I have substantially updated and revised the wiki, including fixing all broken links and link text, and adding a long page detailing the demonstration dataset

I also tested and updated that dataset (downloads are faster as a github release: https://github.com/Doodleverse/segmentation_gym/releases/tag/v0.0.4-testdata). I will make available on zenodo too (it will take hours to upload)

**Comment by dbuscombe-usgs** [comment]
I think I can mark this closed, but feel free to reopen if you notice confusing parts or errors
