### ISSUE TITLE
Metrics at the end of Train.py

### ISSUE THREAD

**Issue by ebgoldstein** [Doodleverse/segmentation_gym#84]
We need to investigate the confusion matrix metrics developed at the end of train.py...

- [x] determine if and how do they differ compared to the mIOU and Dice scores generated during model training..
- [ ] #89

**Comment by dbuscombe-usgs** [comment]
mIOU and Dice scores generated during model training are now identical to those generated during evaluation (uses the same function, just modified to input NCLASSES, and output a numpy scalar)

this is already implemented in this branch of the code: https://github.com/Doodleverse/segmentation_gym/tree/new_makedatasets
